name: trackus
description: A tracker for your focus, trackus (no user tracker included)
version: 1.0.0+1
publish_to: none

isar_version: &isar_version 3.1.0 # define the version to be used

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  generate: true
