name: trackus
description: A tracker for your focus, trackus (no user tracker included)
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  slang: ^3.30.2
  slang_flutter: ^3.30.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  isar_generator: 3.1.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  generate: true
