name: trackus
description: A simple and local todo tracker app for your daily life.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.3
  slang: ^3.31.1
  slang_flutter: ^3.30.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  isar_generator: ^3.1.0
  mocktail: ^1.0.3
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
