import 'package:flutter/material.dart';

final defaultColor = projectColors.first;

final projectColors = [
  Colors.red,
  Colors.orange,
  Colors.yellow,
  Colors.green,
  Colors.blue,
  Colors.indigo,
  Colors.purple,
  Colors.pink,
  Colors.brown,
  Colors.grey,
  Colors.teal,
  Colors.cyan,
  Colors.lime,
  Colors.amber,
  Colors.brown,
  Colors.grey,
  Colors.teal,
  Colors.cyan,
  Colors.deepOrange,
  Colors.deepPurple,
  Colors.blueGrey,
  Colors.redAccent,
  Colors.orangeAccent,
  Colors.yellowAccent,
  Colors.greenAccent,
  Colors.blueAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.pinkAccent,
  Colors.limeAccent,
  Colors.amberAccent,
  Colors.deepOrangeAccent,
  Colors.deepPurpleAccent,
  Colors.white,
];
